### ISSUE TITLE
Rename Repo to aad-b2c-tools

### ISSUE THREAD

**Issue by spottedmahn** [yoelhor/aad-b2c-tools#1]
I think `aad-b2c-tools` is much easier to read then `addb2ctools`.  Thoughts?

**Comment by spottedmahn** [comment]
Well, that was quick ⚡!

![image](https://user-images.githubusercontent.com/14079228/39430358-a643ace6-4c5b-11e8-9c9e-5befd6049dd8.png)

**Comment by yoelhor** [comment]
Yep 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
